on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: main
jobs:
  wasm-x86:
    name: 'WASM (x86)'
    container:
      image: emscripten/emsdk:3.1.42
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set permission all sh files
      if: ${{ env.ACT }}
      run: |
        chmod +x build/wasm-x86/*.sh
        chmod +x build/libraries/*.sh
        chmod +x build/shared/*.sh
        chmod +x src/ImageMagick/*.sh

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/wasm-x86

    - name: Update ImageMagick.commit to latest commit
      run: ./update.imagemagick.sh
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      working-directory: src/ImageMagick

    - name: Clone ImageMagick libraries
      run: ./checkout.sh wasm ../../../artifacts
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/shared/build.Libraries.sh ../../../build/libraries wasm x86
      working-directory: src/ImageMagick/libraries

    - name: Build ImageMagick
      run: ../../../build/shared/build.ImageMagick.sh wasm x86
      working-directory: src/ImageMagick/libraries

    - name: Build Native
      run: ../../build/shared/build.Native.sh wasm x86
      working-directory: src/Magick.Native

    - name: Create type definition
      run: npm install && npm run publish
      working-directory: src/create-type-definition

    - name: Copy Native
      run: ../../build/wasm-x86/copy.Native.sh ../../artifacts
      working-directory: src/Magick.Native

    - name: Upload library
      uses: actions/upload-artifact@v3
      with:
        name: wasm-x86
        path: artifacts
