on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

name: main
jobs:
  wasm:
    name: 'WASM (x86)'
    container:
      image: emscripten/emsdk:3.1.42
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/wasm-x86

    - name: Update ImageMagick.commit to latest commit
      run: ./update.imagemagick.sh
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      working-directory: src/ImageMagick

    - name: Clone ImageMagick libraries
      run: ./checkout.sh wasm ../../../artifacts
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/shared/build.Libraries.sh ../../../build/libraries wasm x86
      working-directory: src/ImageMagick/libraries

    - name: Build ImageMagick
      run: ../../../build/shared/build.ImageMagick.sh wasm x86
      working-directory: src/ImageMagick/libraries

    - name: Build Native
      run: ../../build/shared/build.Native.sh wasm x86
      working-directory: src/Magick.Native

    - name: Create type definition
      run: npm install && npm run publish
      working-directory: src/create-type-definition

    - name: Copy Native
      run: ../../build/wasm-x86/copy.Native.sh ../../artifacts
      working-directory: src/Magick.Native

    - name: Upload library
      uses: actions/upload-artifact@v3
      with:
        name: wasm
        path: artifacts

  metadata:
    name: 'Metadata'
    needs:
      - wasm
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.ps1
      working-directory: build/windows

    - name: Update ImageMagick.commit to latest commit
      run: ./update.imagemagick.cmd
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      working-directory: src/ImageMagick

    - name: Clone ImageMagick libraries
      run: ./checkout.cmd
      working-directory: src/ImageMagick

    - name: Create metadata
      run: ./create.metadata.ps1 -destination ../../artifacts
      working-directory: build/metadata

    - name: Upload metadata
      uses: actions/upload-artifact@v3
      with:
        name: metadata
        path: artifacts
